[Dictionary]
DisplayName=Hrvatski (Hrvatska)
DisplayName[zh_CN]=克罗地亚语 (克罗地亚)
DisplayName[en_US]=Croatian (Croatia)
DisplayName[es_ES]=Croata (Croacia)
DisplayName[zh_TW]=克羅埃西亞文 (克羅埃西亞)
DisplayName[zh_HK]=克羅埃西亞文 (克羅埃西亞)
DisplayName[zh_MO]=克羅埃西亞文 (克羅埃西亞)
DisplayName[zh_Hant_CN]=克羅埃西亞文 (克羅埃西亞)
