[Dictionary]
DisplayName=Español (Guatemala)
DisplayName[zh_CN]=西班牙语 (危地马拉)
DisplayName[en_US]=Spanish (Guatemala)
DisplayName[es_ES]=Español (Guatemala)
DisplayName[zh_TW]=西班牙文 (瓜地馬拉)
DisplayName[zh_HK]=西班牙文 (瓜地馬拉)
DisplayName[zh_MO]=西班牙文 (瓜地馬拉)
DisplayName[zh_Hant_CN]=西班牙文 (瓜地馬拉)
