[Dictionary]
DisplayName=English (South Africa)
DisplayName[zh_CN]=英语 (南非)
DisplayName[en_US]=English (South Africa)
DisplayName[es_ES]=Inglés (Sudáfrica)
DisplayName[zh_TW]=英文 (南非)
DisplayName[zh_HK]=英文 (南非)
DisplayName[zh_MO]=英文 (南非)
DisplayName[zh_Hant_CN]=英文 (南非)
