[Display]
contracts and agreements = 合同協議
company cooperation agreement = 公司合作協議
investment cooperation agreement = 投資合作協議
labor contract = 勞動合同
letter of attorney = 授權委託書
office rental contract = 辦公租賃合同
purchase and sale contract = 購銷合同
purchase contract = 採購合同
share transfer agreement = 股份轉讓協議
shareholding agreement = 股份代持協議

plans and reports = 計畫報告
annual business plan = 經營計畫書
bidding document = 投標檔
business plan = 商業計畫書
event plan = 活動策劃書
meeting summary = 會議紀要
project plan = 專案計畫書

Arabic = 阿拉伯語空白模板

;3087E4A86691363BAA2B5CDE4F75C09D3C887EA91D020E7DE99F31CD323F778E245527515C90D2021ACE1D7025AA29B7CB4BE4B05DCE986077EE099AC45151F2