[Dictionary]
DisplayName=Português (Portugal)
DisplayName[de_DE]=Portugiesisch (Portugal)
DisplayName[en_US]=Portuguese (Portugal)
DisplayName[es_ES]=Portugués (Portugal)
DisplayName[fr_FR]=Portugais (Portugal)
DisplayName[id_ID]=Portugis (Portugal)
DisplayName[pl_PL]=Portugalski (Portugalia)
DisplayName[pt_BR]=Português (Portugal)
DisplayName[pt_PT]=Português (Portugal)
DisplayName[ru_RU]=Португальский (Португалия)
DisplayName[tr_TR]=Portekizce (Portekiz)
DisplayName[zh_CN]=葡萄牙语 (葡萄牙)
DisplayName[zh_TW]=葡萄牙文 (葡萄牙)
DisplayName[zh_HK]=葡萄牙文 (葡萄牙)
DisplayName[zh_MO]=葡萄牙文 (葡萄牙)
DisplayName[zh_Hant_CN]=葡萄牙文 (葡萄牙)
