[Dictionary]
DisplayName=Español (Cuba)
DisplayName[zh_CN]=西班牙语 (古巴)
DisplayName[en_US]=Spanish (Cuba)
DisplayName[es_ES]=Español (Cuba)
DisplayName[zh_TW]=西班牙文 (古巴)
DisplayName[zh_HK]=西班牙文 (古巴)
DisplayName[zh_MO]=西班牙文 (古巴)
DisplayName[zh_Hant_CN]=西班牙文 (古巴)
