[Display]
Government = " Government"
Business = Business
Daily life = Daily Life
Education = Education
Letters and Faxes = Letters and Faxes
Personal = Personal

Internal = หนังสือภายใน
External = หนังสือภายนอก
Seal = หนังสือประทับตรา
MeetingReport = รายงานการประชุม
Announcements = หนังสือแถลงการณ์
Publicity = หนังสือประชาสัมพันธ์
CertifyingLetter = หนังสือรับรอง
Order = หนังสือสั่งการ
;32FA1F9480D4603859944E5CD6121F9664A6DC688172ADB3A725FCB53D8E22EC66DDF3FED70FE3F100E43F88D1413848785BD7FB69991CDA236E6635E71449EF