[Dictionary]
DisplayName=Bahasa Indonesia
DisplayName[de_DE]=Indonesisch
DisplayName[en_US]=Indonesian
DisplayName[es_ES]=Indonesio
DisplayName[fr_FR]=Indonésien
DisplayName[id_ID]=Bahasa Indonesia
DisplayName[pl_PL]=Indonezyjski
DisplayName[pt_BR]=Indonésio
DisplayName[pt_PT]=Indonésio
DisplayName[ru_RU]=Индонезийский
DisplayName[tr_TR]=Endonezce
DisplayName[zh_CN]=印度尼西亚语
DisplayName[zh_TW]=印尼文
DisplayName[zh_HK]=印尼文
DisplayName[zh_MO]=印尼文
DisplayName[zh_Hant_CN]=印尼文
