[Dictionary]
DisplayName=Español (Honduras)
DisplayName[zh_CN]=西班牙语 (洪都拉斯)
DisplayName[en_US]=Spanish (Honduras)
DisplayName[es_ES]=Español (Honduras)
DisplayName[zh_TW]=西班牙文 (洪都拉斯)
DisplayName[zh_HK]=西班牙文 (洪都拉斯)
DisplayName[zh_MO]=西班牙文 (洪都拉斯)
DisplayName[zh_Hant_CN]=西班牙文 (洪都拉斯)
