[Display]
all = 全部範本
black and white = 通用範本-黑白
company intro = 企業宣傳
green for general = 通用範本-翠綠
personal review = 個人述職
project intro = 方案介紹
team report = 總結彙報

Arabic = 阿拉伯語空白模板
;18B6F8295A3DCEC98E70343E46DC8DC7EF15967E7D1148D78D3DBB61B4C13EE316D148D6EBEE5969F9B2B71CFABF01D2CAE0440366369A195CA9279E7023FFD9