[Dictionary]
DisplayName=Deutsch (Österreich)
DisplayName[zh_CN]=德语 (奥地利)
DisplayName[en_US]=German (Austria)
DisplayName[es_ES]=Alemán (Austria)
DisplayName[zh_TW]=德文 (奧地利)
DisplayName[zh_HK]=德文 (奧地利)
DisplayName[zh_MO]=德文 (奧地利)
DisplayName[zh_Hant_CN]=德文 (奧地利)
