[Dictionary]
DisplayName=Español (República Dominicana)
DisplayName[zh_CN]=西班牙语 (多米尼加共和国)
DisplayName[en_US]=Spanish (Dominican Republic)
DisplayName[es_ES]=Español (República Dominicana)
DisplayName[zh_TW]=西班牙文 (多明尼加共和國)
DisplayName[zh_HK]=西班牙文 (多明尼加共和國)
DisplayName[zh_MO]=西班牙文 (多明尼加共和國)
DisplayName[zh_Hant_CN]=西班牙文 (多明尼加共和國)
