[Dictionary]
DisplayName=Deutsch (Deutschland)
DisplayName[de_DE]=Deutsch (Deutschland)
DisplayName[en_US]=German (Germany)
DisplayName[es_ES]=Alemán (Alemania)
DisplayName[fr_FR]=Allemand (Allemagne)
DisplayName[id_ID]=Jerman (Jerman)
DisplayName[pl_PL]=Niemiecki (Niemcy)
DisplayName[pt_BR]=Alemão (Alemanha)
DisplayName[pt_PT]=Alemão (Alemanha)
DisplayName[ru_RU]=Немецкий (Германия)
DisplayName[tr_TR]=Almanca (Almanya)
DisplayName[zh_CN]=德语 (德国)
DisplayName[zh_TW]=德文 (德國)
DisplayName[zh_HK]=德文 (德國)
DisplayName[zh_MO]=德文 (德國)
DisplayName[zh_Hant_CN]=德文 (德國)
