[Dictionary]
DisplayName=ភាសាខ្មែរ (កម្ពុជា)
DisplayName[zh_CN]=高棉语 (柬埔寨)
DisplayName[en_US]=Khmer (Cambodia)
DisplayName[es_ES]=Jemer (Camboya)
DisplayName[zh_TW]=高棉文 (柬埔寨)
DisplayName[zh_HK]=高棉文 (柬埔寨)
DisplayName[zh_MO]=高棉文 (柬埔寨)
DisplayName[zh_Hant_CN]=高棉文 (柬埔寨)
