[Dictionary]
DisplayName=Español (Filipinas)
DisplayName[zh_CN]=西班牙语 (菲律宾)
DisplayName[en_US]=Spanish (Philippines)
DisplayName[es_ES]=Español (Filipinas)
DisplayName[zh_TW]=西班牙文 (菲律賓)
DisplayName[zh_HK]=西班牙文 (菲律賓)
DisplayName[zh_MO]=西班牙文 (菲律賓)
DisplayName[zh_Hant_CN]=西班牙文 (菲律賓)
