[Dictionary]
DisplayName=Español (Perú)
DisplayName[zh_CN]=西班牙语 (秘鲁)
DisplayName[en_US]=Spanish (Peru)
DisplayName[es_ES]=Español (Perú)
DisplayName[zh_TW]=西班牙文 (秘魯)
DisplayName[zh_HK]=西班牙文 (秘魯)
DisplayName[zh_MO]=西班牙文 (秘魯)
DisplayName[zh_Hant_CN]=西班牙文 (秘魯)
