[Dictionary]
DisplayName=Deutsch (Schweiz)
DisplayName[zh_CN]=德语 (瑞士)
DisplayName[en_US]=German (Switzerland)
DisplayName[es_ES]=Alemán (Suiza)
DisplayName[zh_TW]=德文 (瑞士)
DisplayName[zh_HK]=德文 (瑞士)
DisplayName[zh_MO]=德文 (瑞士)
DisplayName[zh_Hant_CN]=德文 (瑞士)
